//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Generated by EasySwiftArc
//  https://github.com/anioutkazharkova/easy-swift-arc

protocol I___VARIABLE_module___Presenter {
//protocol for presenter
    var view: I___VARIABLE_module___View? {get set}
}

class ___VARIABLE_module___Presenter: I___VARIABLE_module___Presenter {
    
   private weak var view: I___VARIABLE_module___View?
    
   static func setup(view: I___VARIABLE_module___View?)->I___VARIABLE_module___Presenter{
        let presenter = ___VARIABLE_module___Presenter()
        presenter.view = view
        return presenter
   }  
}
