//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Generated by EasySwiftArc
//  https://github.com/anioutkazharkova/easy-swift-arc

import UIKit

protocol I___VARIABLE_module___View {
//protocol for View
    
}

class ___VARIABLE_module___VC: UICollectionViewController {
    
   private lazy var presenter: I___VARIABLE_module___Presenter? = {
      return ___VARIABLE_module___Presenter.setup(view: self)
   }()
    
    // MARK: Object lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    
}

extension ___VARIABLE_module___VC: I___VARIABLE_module___View {

}